---
title: "KMeans in RMarkdown"
author: "Kamal Raj Kashyap"
date: "10 June 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("cluster")
library(cluster)
#install.packages("factoextra")
library(factoextra)
#install.packages("ggplot2")
library(ggplot2)
#install.packages("factoextra")
library(factoextra)


data(USArrests)
head(USArrests)
df <- USArrests
df <- scale(df)
head(df)
```
```{r}
k2 <- kmeans(df, centers = 2, nstart = 25)
str(k2)
fviz_cluster(k2, data = df)
```
```{r}
df %>%
  as_tibble() %>%
  mutate(cluster = k2$cluster,
         state = row.names(USArrests)) %>%
  ggplot(aes(UrbanPop, Murder, color = factor(cluster), label = state)) +
  geom_text()
```
```{r}
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)

p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point", data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point", data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point", data = df) + ggtitle("k = 5")
```

```{r}
library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2)
```

